os: linux
dist: bionic
language: python
services:
  - redis
python:
  - '3.8' # Previous version
  - '3.9' # Current version
  # - '3.10' # Future version - not available yet
# command to install dependencies
install:
  - pip install -r requirements.txt && ./setup.py install
before_script:
  - ./prepare_environment.sh
  - python feed_redis.py
# command to run tests
script:
  - pytest
