os: linux
dist: xenial
language: python
services:
  - redis
python:
  - '3.7' # Previous version
  - '3.8' # Current version
  - '3.9' # Future version
# command to install dependencies
install:
  - pip install -r requirements.txt && ./setup.py install
before_script:
  - ./prepare_environment.sh
  - python feed_redis.py
# command to run tests
script:
  - pytest
