[tool.black]
exclude = [".git", "__pycache__", "docs/source/conf.py", "old", "build", "dist", "venv", "__init__.py", "./lib/*", "./bin/*"]
line-length = 120
skip-string-normalization = true

[tool.isort]
skip = [".git", "__pycache__", "docs/source/conf.py", "old", "build", "dist", "venv", "__init__.py"]
skip_glob = ["./lib/*", "./bin/*"]
line_length = 120
use_parentheses = true